# https://dart.dev/guides/language/analysis-options
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/common/di.config.dart
    - lib/**/*.g.dart

# https://dart-lang.github.io/linter/lints/index.html.
linter:
  rules:
    - require_trailing_commas